### ISSUE TITLE
Error executing action `run` on resource 'execute[bin/plugin install logstash-output-influxdb]'

### ISSUE THREAD

**Issue by sagar1730** [lusis/chef-logstash#436]
Got this error while testing Logstash on Vagrant with Chef-solo. 
My Vagrant File is...

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
   config.berkshelf.berksfile_path = "cookbooks/logstash/Berksfile"
  config.berkshelf.enabled = true
   config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "cookbooks"
      chef.add_recipe "java::default"
     chef.add_recipe "logstash::server"
   end
end

I can't resolve the issue. One more thing if I need to upgrade logstash from 1.5.4 to 1.5.5 by changing the URL and commenting Checksum line (to disable) then will it work.

**Comment by spuder** [comment]
Logstash has a build that includes all the plugins by default. The plugin resource isn't idempotent. 


```yaml
    attributes:
      java:
        jdk_version: 7
      logstash:
        instance_default:
          version: "2.1.0"
          source_url: "https://download.elastic.co/logstash/logstash/logstash-all-plugins-2.1.0.tar.gz"
          checksum: "090cca8b1d7584ed7f3a60abd4e5f4329cf36f41481de80982fee709e2febf58"
```
